### ISSUE TITLE
Failure to compile with GHC 8.6

### ISSUE THREAD

**Issue by ivanperez-keera** [fdedden/language-c99-simple#1]
Things have changed in base 4.12. This library no longer compiles:

```
Configuring language-c99-simple-0.1.0.0...
Building language-c99-simple-0.1.0.0...
Preprocessing library language-c99-simple-0.1.0.0...
[1 of 5] Compiling Language.C99.Simple.AST ( src/Language/C99/Simple/AST.hs, dist/dist-sandbox-11467d12/build/Language/C99/Simple/AST.o )
[2 of 5] Compiling Language.C99.Simple.Expr ( src/Language/C99/Simple/Expr.hs, dist/dist-sandbox-11467d12/build/Language/C99/Simple/Expr.o )
[3 of 5] Compiling Language.C99.Simple.Util ( src/Language/C99/Simple/Util.hs, dist/dist-sandbox-11467d12/build/Language/C99/Simple/Util.o )
[4 of 5] Compiling Language.C99.Simple.Translate ( src/Language/C99/Simple/Translate.hs, dist/dist-sandbox-11467d12/build/Language/C99/Simple/Translate.o )

src/Language/C99/Simple/Translate.hs:302:5: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         Data.Functor.Identity.Identity)
        arising from a do statement
        with the failable pattern ‘(C.AbstractDeclrDirect ptr adeclr)’
```

**Comment by ivanperez-keera** [comment]
The failure is due to Identity not having an instance of MonadFail and using an irrefutable pattern.

Solutions are described here: https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail#Adaptingoldcode

Also, a lazy pattern makes the problem go away, but that could change the meaning of the program.

**Comment by fdedden** [comment]
The problem should be fixed with the latest commit.

**Comment by ivanperez-keera** [comment]
Ok. If you Ref #1 in the commit message, you don't have to comment later.
